/*
 * ILPCR - Indoor Localization by Point Cloud Registration
 * Copyright (C) 2024 Christian Roedlach
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * 
 * File:            presets.cpp
 * Description:     ILPCR presets system
 */

#include "types.h"

namespace ilpcr 
{
/* RS2 filter presets */
    const rs2_filter_settings_t rs2_filter_presets[rs2_filter_preset_count] = {
        /* Ignoring warning as this unititialized preset is never used */
        {
            .preset             = rs2_filter_preset_undefined,
            .preset_name        = "undefined",
            .rs2_config_file    = "undefined",
            .limit_min          = 0,
            .limit_max          = 0,
            .dec_fil_enable     = false,
            .dec_fil_magnitude  = 0,
            .spa_fil_enable     = false,
            .spa_fil_magnitude  = 0,
            .spa_fil_alpha      = 0,
            .spa_fil_delta      = 0,
            .spa_fil_holes_fill = 0,
            .tem_fil_enable     = false,
            .tem_fil_alpha      = 0,
            .tem_fil_delta      = 0,
            .tem_fil_pers_ctl   = 0
        },
        {
            .preset             = rs2_filter_preset_1,
            .preset_name        = "p1",
            .rs2_config_file    = "high_density.json",
            .limit_min          = 0.3f,
            .limit_max          = 5.0f,
            .dec_fil_enable     = true,
            .dec_fil_magnitude  = 2.0,
            .spa_fil_enable     = true,
            .spa_fil_magnitude  = 5.0,
            .spa_fil_alpha      = 0.25,
            .spa_fil_delta      = 15,
            .spa_fil_holes_fill = 2,
            .tem_fil_enable     = true,
            .tem_fil_alpha      = 0.60,
            .tem_fil_delta      = 19,
            .tem_fil_pers_ctl   = 3
        },
        {
            .preset             = rs2_filter_preset_2,
            .preset_name        = "p2",
            .rs2_config_file    = "high_density.json",
            .limit_min          = 0.3f,
            .limit_max          = 8.0f,
            .dec_fil_enable     = true,
            .dec_fil_magnitude  = 2.0,
            .spa_fil_enable     = true,
            .spa_fil_magnitude  = 5.0,
            .spa_fil_alpha      = 0.25,
            .spa_fil_delta      = 15,
            .spa_fil_holes_fill = 2,
            .tem_fil_enable     = true,
            .tem_fil_alpha      = 0.60,
            .tem_fil_delta      = 19,
            .tem_fil_pers_ctl   = 3
        },
        {
            .preset             = rs2_filter_preset_1a,
            .preset_name        = "p1a",
            .rs2_config_file    = "high_accuracy.json",
            .limit_min          = 0.3f,
            .limit_max          = 5.0f,
            .dec_fil_enable     = true,
            .dec_fil_magnitude  = 2.0,
            .spa_fil_enable     = true,
            .spa_fil_magnitude  = 5.0,
            .spa_fil_alpha      = 0.25,
            .spa_fil_delta      = 15,
            .spa_fil_holes_fill = 2,
            .tem_fil_enable     = true,
            .tem_fil_alpha      = 0.60,
            .tem_fil_delta      = 19,
            .tem_fil_pers_ctl   = 3
        },
        {
            .preset             = rs2_filter_preset_2a,
            .preset_name        = "p2a",
            .rs2_config_file    = "high_accuracy.json",
            .limit_min          = 0.3f,
            .limit_max          = 8.0f,
            .dec_fil_enable     = true,
            .dec_fil_magnitude  = 2.0,
            .spa_fil_enable     = true,
            .spa_fil_magnitude  = 5.0,
            .spa_fil_alpha      = 0.25,
            .spa_fil_delta      = 15,
            .spa_fil_holes_fill = 2,
            .tem_fil_enable     = true,
            .tem_fil_alpha      = 0.60,
            .tem_fil_delta      = 19,
            .tem_fil_pers_ctl   = 3
        },
        {
            .preset             = rs2_filter_preset_3,
            .preset_name        = "p3",
            .rs2_config_file    = "high_density.json",
            .limit_min          = 0.3f,
            .limit_max          = 10.4f,
            .dec_fil_enable     = true,
            .dec_fil_magnitude  = 4.0,
            .spa_fil_enable     = true,
            .spa_fil_magnitude  = 4.0,
            .spa_fil_alpha      = 0.4,
            .spa_fil_delta      = 12,
            .spa_fil_holes_fill = 2,
            .tem_fil_enable     = true,
            .tem_fil_alpha      = 0.1,
            .tem_fil_delta      = 80,
            .tem_fil_pers_ctl   = 1
        },
        {
            .preset             = rs2_filter_preset_3a,
            .preset_name        = "p3a",
            .rs2_config_file    = "high_accuracy.json",
            .limit_min          = 0.3f,
            .limit_max          = 10.4f,
            .dec_fil_enable     = true,
            .dec_fil_magnitude  = 4.0,
            .spa_fil_enable     = true,
            .spa_fil_magnitude  = 4.0,
            .spa_fil_alpha      = 0.4,
            .spa_fil_delta      = 12,
            .spa_fil_holes_fill = 2,
            .tem_fil_enable     = true,
            .tem_fil_alpha      = 0.1,
            .tem_fil_delta      = 80,
            .tem_fil_pers_ctl   = 1
        },
        {
            .preset             = rs2_filter_preset_4,
            .preset_name        = "p4",
            .rs2_config_file    = "high_density.json",
            .limit_min          = 0.3f,
            .limit_max          = 10.4f,
            .dec_fil_enable     = true,
            .dec_fil_magnitude  = 1.0,
            .spa_fil_enable     = true,
            .spa_fil_magnitude  = 4.0,
            .spa_fil_alpha      = 0.4,
            .spa_fil_delta      = 12,
            .spa_fil_holes_fill = 2,
            .tem_fil_enable     = true,
            .tem_fil_alpha      = 0.1,
            .tem_fil_delta      = 80,
            .tem_fil_pers_ctl   = 1
        },
        {
            .preset             = rs2_filter_preset_4a,
            .preset_name        = "p4a",
            .rs2_config_file    = "high_accuracy.json",
            .limit_min          = 0.3f,
            .limit_max          = 10.4f,
            .dec_fil_enable     = true,
            .dec_fil_magnitude  = 1.0,
            .spa_fil_enable     = true,
            .spa_fil_magnitude  = 4.0,
            .spa_fil_alpha      = 0.4,
            .spa_fil_delta      = 12,
            .spa_fil_holes_fill = 2,
            .tem_fil_enable     = true,
            .tem_fil_alpha      = 0.1,
            .tem_fil_delta      = 80,
            .tem_fil_pers_ctl   = 1
        },
        {
            .preset             = rs2_filter_preset_5,
            .preset_name        = "p5",
            .rs2_config_file    = "high_density.json",
            .limit_min          = 0.3f,
            .limit_max          = 10.4f,
            .dec_fil_enable     = true,
            .dec_fil_magnitude  = 3.0,
            .spa_fil_enable     = true,
            .spa_fil_magnitude  = 4.0,
            .spa_fil_alpha      = 0.4,
            .spa_fil_delta      = 12,
            .spa_fil_holes_fill = 2,
            .tem_fil_enable     = true,
            .tem_fil_alpha      = 0.1,
            .tem_fil_delta      = 80,
            .tem_fil_pers_ctl   = 1
        },
        {
            .preset             = rs2_filter_preset_5a,
            .preset_name        = "p5a",
            .rs2_config_file    = "high_accuracy.json",
            .limit_min          = 0.3f,
            .limit_max          = 10.4f,
            .dec_fil_enable     = true,
            .dec_fil_magnitude  = 3.0,
            .spa_fil_enable     = true,
            .spa_fil_magnitude  = 4.0,
            .spa_fil_alpha      = 0.4,
            .spa_fil_delta      = 12,
            .spa_fil_holes_fill = 2,
            .tem_fil_enable     = true,
            .tem_fil_alpha      = 0.1,
            .tem_fil_delta      = 80,
            .tem_fil_pers_ctl   = 1
        },
        {
            .preset             = rs2_filter_preset_6,
            .preset_name        = "p6",
            .rs2_config_file    = "high_density.json",
            .limit_min          = 0.3f,
            .limit_max          = 10.4f,
            .dec_fil_enable     = true,
            .dec_fil_magnitude  = 3.0,
            .spa_fil_enable     = true,
            .spa_fil_magnitude  = 4.0,
            .spa_fil_alpha      = 0.4,
            .spa_fil_delta      = 12,
            .spa_fil_holes_fill = 2,
            .tem_fil_enable     = false,
            .tem_fil_alpha      = 0.1,
            .tem_fil_delta      = 80,
            .tem_fil_pers_ctl   = 1
        },
        {
            .preset             = rs2_filter_preset_6a,
            .preset_name        = "p6a",
            .rs2_config_file    = "high_accuracy.json",
            .limit_min          = 0.3f,
            .limit_max          = 10.4f,
            .dec_fil_enable     = true,
            .dec_fil_magnitude  = 3.0,
            .spa_fil_enable     = true,
            .spa_fil_magnitude  = 4.0,
            .spa_fil_alpha      = 0.4,
            .spa_fil_delta      = 12,
            .spa_fil_holes_fill = 2,
            .tem_fil_enable     = false,
            .tem_fil_alpha      = 0.1,
            .tem_fil_delta      = 80,
            .tem_fil_pers_ctl   = 1
        }
    };

    /* RANSAC SampleConsensusPrerejective presets */
    const pcr_settings_t pcr_presets[pcr_names_count] = {
        {
            .preset                     = pcr_preset_undefined,
            .preset_name                = "undefined",
            .max_iterations             = 0,
            .nr_of_samples              = 0,
            .corr_rand                  = 0,
            .sim_threshold              = 0,
            .max_corr_distance          = 0,
            .inlier_fraction            = 0,
            .raster_size                = 0,
            .feature_search_radius      = 0,
            .nest_search_radius         = 0,
            .processing_unit            = ilpcr_proc_type_cpu,
            .use_normal_surface_search  = false,
        },
        {
            .preset                     = pcr_preset_narf_1,
            .preset_name                = "narf_1",
            .max_iterations             = 300000,
            .nr_of_samples              = 3,
            .corr_rand                  = 15,
            .sim_threshold              = 0.85,
            .max_corr_distance          = 0.20,
            .inlier_fraction            = 0.80,
            .raster_size                = 0,
            .feature_search_radius      = 0,
            .nest_search_radius         = 0,
            .processing_unit            = ilpcr_proc_type_cpu,
            .use_normal_surface_search  = false,
        },
        {
            .preset                     = pcr_preset_fpfh_1,
            .preset_name                = "fpfh_1",
            .max_iterations             = 1000000,
            .nr_of_samples              = 3,
            .corr_rand                  = 5,
            .sim_threshold              = 0.95,
            .max_corr_distance          = 0.25,
            .inlier_fraction            = 0.80,
            .raster_size                = 0.1,
            .feature_search_radius      = 0.5,
            .nest_search_radius         = 0.5,
            .processing_unit            = ilpcr_proc_type_cpu,
            .use_normal_surface_search  = true,
        },
        {
            .preset                     = pcr_preset_fpfh_2,
            .preset_name                = "fpfh_2",
            .max_iterations             = 500000,
            .nr_of_samples              = 3,
            .corr_rand                  = 5,
            .sim_threshold              = 0.95,
            .max_corr_distance          = 0.25,
            .inlier_fraction            = 0.80,
            .raster_size                = 0.1,
            .feature_search_radius      = 0.5,
            .nest_search_radius         = 0.5,
            .processing_unit            = ilpcr_proc_type_cpu,
            .use_normal_surface_search  = true,
        },
        {
            .preset                     = pcr_preset_fpfh_3,
            .preset_name                = "fpfh_3",
            .max_iterations             = 1000000,
            .nr_of_samples              = 3,
            .corr_rand                  = 5,
            .sim_threshold              = 0.95,
            .max_corr_distance          = 0.6,
            .inlier_fraction            = 0.90,
            .raster_size                = 0.1,
            .feature_search_radius      = 1.8,
            .nest_search_radius         = 0.7,
            .processing_unit            = ilpcr_proc_type_cpu,
            .use_normal_surface_search  = true,
        },
        {
            .preset                     = pcr_preset_fpfh_4,
            .preset_name                = "fpfh_4",
            .max_iterations             = 5000000,
            .nr_of_samples              = 3,
            .corr_rand                  = 5,
            .sim_threshold              = 0.93,
            .max_corr_distance          = 0.3,
            .inlier_fraction            = 0.96,
            .raster_size                = 0.1,
            .feature_search_radius      = 0.65,
            .nest_search_radius         = 0.25,
            .processing_unit            = ilpcr_proc_type_cpu,
            .use_normal_surface_search  = true,
        },
        {
            .preset                     = pcr_preset_fpfh_5cu,
            .preset_name                = "fpfh_5cu",
            .max_iterations             = 128,
            .nr_of_samples              = 0,
            .corr_rand                  = 0,
            .sim_threshold              = 0.95,
            .max_corr_distance          = 0.60,
            .inlier_fraction            = 0.78,
            .raster_size                = 0.10,
            .feature_search_radius      = 1.8,
            .nest_search_radius         = 0.7,
            .processing_unit            = ilpcr_proc_type_fgr_gpu,
            .use_normal_surface_search  = true,
        },
        {
            .preset                     = pcr_preset_fpfh_5_fpfh_fgr_gpu,
            .preset_name                = "fpfh_5_fpfh_fgr_gpu",
            .max_iterations             = 128,
            .nr_of_samples              = 0,
            .corr_rand                  = 0,
            .sim_threshold              = 0.95,
            .max_corr_distance          = 0.60,
            .inlier_fraction            = 0.78,
            .raster_size                = 0.10,
            .feature_search_radius      = 1.8,
            .nest_search_radius         = 0.7,
            .processing_unit            = ilpcr_proc_type_fpfh_fgr_gpu,
            .use_normal_surface_search  = true,
        },
    };
}